# Generated by Django 4.1 on 2022-08-12 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionarea', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='aks_by',
            new_name='ask_by',
        ),
    ]
