# Generated by Django 4.1 on 2022-09-04 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionarea', '0002_rename_aks_by_question_ask_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ask_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ask_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_modified', models.DateField(auto_now=True, null=True)),
                ('ans_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ans_by', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questionarea.question')),
            ],
        ),
    ]
